# Generated by Django 5.2.8 on 2026-01-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('encrypted_content', models.BinaryField(blank=True, null=True)),
                ('key_version', models.IntegerField(default=1)),
                ('client_encrypted_content', models.TextField(blank=True, help_text='Client-side encrypted content (base64)', null=True)),
                ('client_iv', models.TextField(blank=True, help_text='Initialization vector for client encryption (base64)', null=True)),
                ('client_encryption_version', models.IntegerField(default=0, help_text='Client encryption version (0=unencrypted, 1=AES-GCM)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted_for_everyone', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this message should disappear', null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('is_voice_message', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('blocked', 'Blocked'), ('pending', 'Pending Message Request'), ('rejected', 'Request Rejected')], default='pending', max_length=20)),
                ('request_status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('none', 'None')], default='none', max_length=20)),
                ('is_group', models.BooleanField(default=False)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('group_image', models.ImageField(blank=True, null=True, upload_to='group_avatars/')),
                ('group_members_can_invite', models.BooleanField(default=True)),
                ('group_members_can_send', models.BooleanField(default=True)),
                ('encryption_key', models.TextField(blank=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('disappearing_messages_duration', models.IntegerField(blank=True, help_text='Duration in seconds before messages disappear', null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('voice', 'Voice Message')], max_length=20)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_name', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='chat_thumbnails/%Y/%m/%d/')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds for audio/video', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_typed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_typed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction_type', models.CharField(choices=[('block', 'Block'), ('mute', 'Mute'), ('restrict', 'Restrict')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
