# Generated by Django 5.2.8 on 2026-01-15 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockeduser',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='forwarded_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_groups', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_threads', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='muted_by',
            field=models.ManyToManyField(blank=True, related_name='muted_threads', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='participants',
            field=models.ManyToManyField(related_name='chat_threads', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='chatthread',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_threads', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='chat.chatmessage'),
        ),
        migrations.AddField(
            model_name='messagereaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='messagerequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='messagerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='messagerequest',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='typingindicator',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='chat.chatthread'),
        ),
        migrations.AddField(
            model_name='typingindicator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typing_in', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='userrestriction',
            name='restricted_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_by', to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='userrestriction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions_set', to='core.userprofile'),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocker'], name='chat_blocke_blocker_b3c3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='blockeduser',
            index=models.Index(fields=['blocked'], name='chat_blocke_blocked_24bf56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together={('blocker', 'blocked')},
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['-updated_at'], name='chat_chatth_updated_5faf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['status'], name='chat_chatth_status_16ea8f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatthread',
            index=models.Index(fields=['request_status'], name='chat_chatth_request_ed770c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'created_at'], name='chat_chatme_thread__b4c881_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['thread', 'read'], name='chat_chatme_thread__bbfc13_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['expires_at'], name='chat_chatme_expires_8d9d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='groupinvitation',
            index=models.Index(fields=['invitee', 'status'], name='chat_groupi_invitee_f76938_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupinvitation',
            unique_together={('group', 'invitee')},
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message'], name='chat_messag_message_bb212c_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['file_type'], name='chat_messag_file_ty_820d59_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message'], name='chat_messag_message_4e17fc_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user'], name='chat_messag_user_id_d967ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='messagerequest',
            index=models.Index(fields=['recipient', 'status'], name='chat_messag_recipie_3beff5_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerequest',
            index=models.Index(fields=['requester', 'status'], name='chat_messag_request_d0ff92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagerequest',
            unique_together={('requester', 'recipient')},
        ),
        migrations.AddIndex(
            model_name='typingindicator',
            index=models.Index(fields=['thread', '-last_typed_at'], name='chat_typing_thread__e626be_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typingindicator',
            unique_together={('thread', 'user')},
        ),
        migrations.AddIndex(
            model_name='userrestriction',
            index=models.Index(fields=['user', 'restriction_type'], name='chat_userre_user_id_0db402_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrestriction',
            unique_together={('user', 'restricted_user', 'restriction_type')},
        ),
    ]
