# Generated by Django 5.2.8 on 2026-01-18 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('core', '0005_alter_sharedpost_chat_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='chatthread',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_groups', to='core.userprofile'),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_groups_legacy', to='core.userprofile'),
        ),
    ]
