# Generated by Django 5.2.8 on 2026-01-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_options_chatthread_admins_and_more'),
        ('core', '0005_alter_sharedpost_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_threads', to='core.userprofile'),
        ),
    ]
