# Generated by Django 5.2.8 on 2026-01-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatthread_hidden_by'),
        ('core', '0006_alter_sharedpost_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_threads', to='core.userprofile'),
        ),
    ]
