# Generated by Django 5.2.8 on 2026-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatthread_deleted_by'),
        ('core', '0006_alter_sharedpost_chat_message'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chatthread',
            constraint=models.UniqueConstraint(condition=models.Q(('is_group', True)), fields=('group_name',), name='unique_group_name'),
        ),
    ]
