# Generated by Django 5.2.8 on 2026-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpost',
            name='chat_message',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
