# Generated by Django 5.2.8 on 2026-01-18 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatthread_hidden_by'),
        ('core', '0005_alter_sharedpost_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedpost',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to='chat.chatmessage'),
        ),
    ]
